logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

jwt:
  private.key: classpath:secrets/app.key
  public.key: classpath:secrets/app.pub

spring:
  datasource:
    url: jdbc:h2:mem:hogwarts
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
server:
   port: 80
